name: SAM Deploy

on:
  push:
    branches: [ main ] # mainブランチにpushされたら起動

permissions:
  id-token: write # OIDCを使うために必須
  contents: read  # ソースコードを読み取るために必須

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} # ここでロールARNを使う
          aws-region: ap-northeast-1

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build and Deploy
        run: |
          sam build
          
          # --config-env を指定し、プロファイルを無視するように設定
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --no-progressbar